<?php

return [
    ['name' => 'Behance', 'code' => 'fab fa-behance'],
    ['name' => 'Codepen', 'code' => 'fab fa-codepen'],
    ['name' => 'Digg', 'code' => 'fab fa-digg'],
    ['name' => 'Dribbble', 'code' => 'fab fa-dribbble'],
    ['name' => 'Facebook', 'code' => 'fab fa-facebook-f'],
    ['name' => 'Flickr', 'code' => 'fab fa-flickr'],
    ['name' => 'Github', 'code' => 'fab fa-github-alt'],
    ['name' => 'Gitlab', 'code' => 'fab fa-gitlab'],
    ['name' => 'Instagram', 'code' => 'fab fa-instagram'],
    ['name' => 'Linkedin', 'code' => 'fab fa-linkedin-in'],
    ['name' => 'Pinterest', 'code' => 'fab fa-pinterest'],
    ['name' => 'QQ', 'code' => 'fab fa-qq'],
    ['name' => 'Reddit', 'code' => 'fab fa-reddit-alien'],
    ['name' => 'Skype', 'code' => 'fab fa-skype'],
    ['name' => 'Slack', 'code' => 'fab fa-slack'],
    ['name' => 'Snapchat', 'code' => 'fab fa-snapchat'],
    ['name' => 'Soundcloud', 'code' => 'fab fa-soundcloud'],
    ['name' => 'Squarespace', 'code' => 'fab fa-squarespace'],
    ['name' => 'Telegram', 'code' => 'fab fa-telegram'],
    ['name' => 'Tiktok', 'code' => 'fab fa-tiktok'],
    ['name' => 'Tumblr', 'code' => 'fab fa-tumblr'],
    ['name' => 'Twitch', 'code' => 'fab fa-twitch'],
    ['name' => 'Twitter', 'code' => 'fab fa-twitter'],
    ['name' => 'Vimeo', 'code' => 'fab fa-vimeo-v'],
    ['name' => 'Whatsapp', 'code' => 'fab fa-whatsapp'],
    ['name' => 'WordPress', 'code' => 'fab fa-wordpress-simple'],
    ['name' => 'Youtube', 'code' => 'fab fa-youtube'],
];
